### ISSUE TITLE
Congratulations! (and a question)

### ISSUE THREAD

**Issue by asheenlevrai** [the0neyouseek/MonitorControl#1]
Wow! your fork looks very neat!

I cannot wait for it to mature a little more and look forward to seeing the stuff you put into TODO implemented in the future :)

For now, I was wondering about how exactly I should use Karabiner Elements and its rules for MonitorControl. Should I install KE? and Then enter the URL you provide into my browser? Excuse my ignorance but could you please elaborate a little bit on how to achieve this?

Thank you so much for your help.
Best,
-a-

**Comment by the0neyouseek** [comment]
Thank you @asheenlevrai,

I'll try to find time to work on this project as I have other ideas that I want to implement. 😄   
As for your question, here's a step by step :

1. Install Karabiner Elements following this link : https://pqrs.org/osx/karabiner/  
(There's a guide on the bottom of the page)
2. Then, open the link from the readme on your browser. This should launch KE and show you this screen :  
![karabiner-elem](https://user-images.githubusercontent.com/4009175/33128807-12032434-cf8e-11e7-8fe4-d6f047178eec.png)
3. Click on `Import`. This should take you to this screen :  
![k2](https://user-images.githubusercontent.com/4009175/33128863-421720c6-cf8e-11e7-8032-0fa9b1aa7bfd.png)
4. Now click on `Enable All` and you're done ! You can close KE and the volume/brightness keys should work

Have a nice day,
@the0neyouseek

**Comment by asheenlevrai** [comment]
Thank you so much for the swift answer :)

Unfortunately my problem is not solved. I don't know where my problem comes from. Let me explain:

After installing **M**onitor**C**ontrol and **K**arabiner**E**lements I experienced the same issue as with other solutions like SoundSiphon and other forks of MC:
 - sound is intermittent (mostly off but then comes back for a second or two every now and then)
 - changing the volume using MC has no effect on the actual volume (when sound is actually audible). Brightness and contrast do work, though.
In addition, I experienced the following (linked to KE, I guess):
 - Whenever pressing F1/F2 or F10-F12 while a desktop icon is selected, the corresponding slider moves in MC but the selected icon on the desktop also changes, suggesting that now these keys perform 2 different actions at the same time...

I feel that since I experience the same problem with multiple apps, y problem could come from my audio driver (kext?) rather than the apps themselves. I run Sierra 10.12.6 that was patched for HDMI/DP audio using this script:
https://www.tonymacx86.com/threads/applehda-hdmi-audio-guide.234735/

Let me know what you think about this.

Thank you very much once again for your help.

Bet,
-a-

PS: my setup:
asus z97-a
i7-4790k
GeForce GTX980
Dell S2817Q monitor over DP (no line-in for audio)

**Comment by the0neyouseek** [comment]
Hi @asheenlevrai,

Here's what I can tell for the problems you mentionned :

- Your sound issue come most certainly from your driver or an incompatible kext, MonitorControl uses [@kfix/ddcctl](https://github.com/kfix/ddcctl) to control brightness/volume so if your monitor is compatible with it it should be fine
- For the shortcut issue with Karabiner Element, I'm aware of it and will try to fix it soon.

Have a nice day !
