### ISSUE TITLE
Add Ukrainian localization

### ISSUE THREAD

**Issue by kikiwora** [the0neyouseek/MonitorControl#101]
It would be great to have a Ukrainian localization.
I already translated localization files and wish to give them to you but have no access right to push as for now.

**Comment by JoniVR** [comment]
You need to open a [Pull Request](https://github.com/the0neyouseek/MonitorControl/pulls) for this.

https://help.github.com/en/articles/about-pull-requests

**Comment by kikiwora** [comment]
Thanks. It seems like I should've created a fork in order to push branch there and then create a pull request in your repo.

**Comment by the0neyouseek** [comment]
Closed from #103
