### ISSUE TITLE
option to set volume increase

### ISSUE THREAD

**Issue by larskochhansen** [the0neyouseek/MonitorControl#106]
Thanks for the amazing app. I love it.

I have a MBP 2018 and a samsung c79 curved display with built in speakers. The problem is that the volumen at lowest level is rather high. I never use a volume more than "the first or second" dot. When I work in the evening it would be great if one could some have change how the volume intervals increase. 

Does it make any sense?
Thanks again,
Best wishes
Lars

**Comment by the0neyouseek** [comment]
Hi,

Thanks for the kind words !

You can actually already do that, by using <kbd>shift</kbd> + <kbd>alt</kbd> and your volume keys it should change volume in smaller increments

Tell me if it works for you 😄

**Comment by larskochhansen** [comment]
I works 👍 
Still, The option to use the "normal" volume keys to adjust volume would be great. Right now I can only use the "two" last volume dots - higher than that is really loud thus making small adjustments troublesome.
