### ISSUE TITLE
No mute after update to version 1.6.0

### ISSUE THREAD

**Issue by iBubelo** [the0neyouseek/MonitorControl#107]
The MonitorControl 1.5.2 used to work just perfectly on my AOC Q2577W. But since I've updated to 1.6.0 I can't mute the sound. Behavior is similar to #94.
Reverting to 1.5.2 fixed the issue.

**Comment by JoniVR** [comment]
Could perhaps be that your monitor doesn't support the ddc mute command implemented in #96. Maybe we could work a fallback into the advanced prefs panel but it'll probably for later versions then. 

I'll try to provide a test build in the future but I'm currently too swamped with other stuff.

**Comment by iBubelo** [comment]
Thank you for swift reply! I'll be happy to help with testing.

**Comment by innovia** [comment]
i have the dell u3419 can't use mute at tall but running the command line utility ddcctl -d 1 -v 0 works

**Comment by scorpiondev** [comment]
@innovia: What happens if you run `ddcctl -d 1 -m \?`

**Comment by innovia** [comment]
@scorpiondev  

```
 ddcctl -d 1 -m
D: NSScreen #724074197 (3440x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: B0GP5T2
I: got edid.name: DELL U3419W
```

**Comment by scorpiondev** [comment]
@innovia: You need to add the ‘ /?’ to the end of that command so we can see the results :)

**Comment by innovia** [comment]
@scorpiondev 

```
➜ ddcctl -d 1 -m \?
D: NSScreen #724074197 (3440x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: B0GP5T2
I: got edid.name: DELL U3419W
D: action: m: ?
D: querying VCP control: #141 =?
I: VCP control #141 (0x8d) = current: 30, max: 100
```

**Comment by scorpiondev** [comment]
@innovia, thanks for that - if I were to take a wild guess, it looks like your monitor maps the mute control to speaker volume, as evidenced by **current: 30, max: 100** as compared to my monitor (output below) where the same control has **current: 2, max: 2** (value of 1 is muted, value of 2 is not).

```
➜ ddcctl -d 1 -m \?
D: NSScreen #188974799 (3440x1440 0°) 110.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: C34J79x
I: got edid.serial: HTRK800598
D: action: m: ?
D: querying VCP control: #141 =?
I: VCP control #141 (0x8d) = current: 2, max: 2
```

@JoniVR: I'm happy to work on both the issue I pointed out in my previous post (feel free to raise a separate issue if you see the need), and also check whether the mute command value has a max above 2 and fallback to setting the speaker volume to 0 - I can get to these later this week or on the weekend.

**Comment by JoniVR** [comment]
@scorpiondev Sounds good to me, no pressure though, feel free to do it whenever you have time or feel like it :)

**Comment by innovia** [comment]
Its working for me - thanks for the fix
