### ISSUE TITLE
Doesn't controll imac in target mode

### ISSUE THREAD

**Issue by Voitus** [the0neyouseek/MonitorControl#108]
Hi,

Great app. Just built hackintosh and I'm using old imac 27 inch 2009 as monitor in target mode via displayport to minidsplayport. App controls other 2 monitors but not imac :-(

**Comment by JoniVR** [comment]
Are you sure ddc is supported on that? 
Try installing a tool called ddcctl (search on Github) and then pasting the output.

**Comment by JoniVR** [comment]
Can you test v1.7.0 and report back please?

**Comment by JoniVR** [comment]
Closing for now since no response.

**Comment by n8gray** [comment]
I've got the same issue. `ddcctl` doesn't seem to work with it. For example, here's the output of `ddcctl -d 1 -b \?`

```
D: NSScreen #69678537 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: Color LCD
D: action: b: ?
D: querying VCP control: #16 =?
E: No data after 10 tries! 
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0
```

Everything I try ends up with `E: DDC send command failed!`

:cry:
