### ISSUE TITLE
Does not work on mac book pro with external screen on Display port

### ISSUE THREAD

**Issue by christianv2m** [the0neyouseek/MonitorControl#117]
- Macbook pro with Mojave 10.14.6.
- CalDigit thunderbolt station (https://www.amazon.es/caldigit-TS3-Plus-Thunderbolt-puertos-DisplayPort/dp/B07CVP5HMP/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=caldigit&qid=1566943834&s=gateway&sr=8-1)
- External screen BenQ 27 inches with Display port.
- The buttons does not affect audio at all.
- Brightness buttons only affects native laptop screen.

**Comment by JoniVR** [comment]
Please see #61
