### ISSUE TITLE
Turning off brightness doesn't work

### ISSUE THREAD

**Issue by funbben** [the0neyouseek/MonitorControl#12]
Hi, thanks for the good work. Apps works fine for Volume and Brightness on my iiyama 27" LED - B2791QSU-B1

Except that I can't dim the brightness to 0%, the progress bar is at 0%, but there is still brightness on the screen. I would say that backlight remains at 15%

**Comment by the0neyouseek** [comment]
Hi @funbben,
I'm gonna have a look at this tomorrow and see if I can reproduce it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funbben** [comment]
Hummm, it might not be a bug. It might be related to the way iiyama implemented brightness dimming.

The monitor OSD says brightness 0%, the only way I found to dim "no light" is to reduce constrast to 0%.

A workaround would be to implement a specific option (in preference menu). It could be called "Force brightness diming" 
The program would first dim down to 0% brightness, and then could still dim down the contrast. to 0%
When turning up, it would first dim up contrast to previous setting, and then dim up the brightness.

Let me know if you want me to do other testing

**Comment by the0neyouseek** [comment]
Hi @funbben,

I've just pushed a new version of the app, please take a look as I've included an option to do just that.  
If you open the new Preference Window, you can now choose the option to "Lower contrast after brightness" which will put your contrast to 0 when brightness hit zero too.

Tell me if it works for you,
Have a nice day

**Comment by funbben** [comment]
Many thanks I installed the latest version, I will be testing it in a couple of days, I'm not at home for now.

**Comment by funbben** [comment]
I just tested, contrast control works fine, but indeed keyboard shortcut doesn't work any more (see issue #14) so I can't really test the combined brightness and contrat dimming

**Comment by falcn** [comment]
I can confirm, it's a safety feature of a many monitors. Dell P2715Q doesn't allow to set contrast below 25% over DDC, only manually (OSD controls).
