### ISSUE TITLE
Release with updated DCC.swift?

### ISSUE THREAD

**Issue by edeis53** [the0neyouseek/MonitorControl#121]
reitermarkus/DDC.swift has been updated with a fix that should allow support for Acer monitors.

Based on update to kfix/ddctl which implement Fix signed/unsigned compare.
https://github.com/kfix/ddcctl/issues/53

@the0neyouseek  Can you issue a release with the DCC.swift dependancy updated to latest commit?
https://github.com/reitermarkus/DDC.swift/commit/41e7c49b0450033c5349ca1cf5234a26ebc011b8

**Comment by edeis53** [comment]
@JoniVR should I create a pull request for this? would you accept?

**Comment by JoniVR** [comment]
I was planning on updating DDC.swift first thing when I get time. Then trying to merge in #116 and then create a release. I’ll try to get that done tomorrow but I can’t promise anything. But a PR is not really necessary since it’s should be pretty easy to do.

**Comment by JoniVR** [comment]
Actually I think I’ll create a release before merging in #116 so we can get these critical fixes out faster.

**Comment by JoniVR** [comment]
New release (v1.7.0) has been created. Please let me know if you run into any issues. I'm going to consider this closed in the meantime. :)

**Comment by edeis53** [comment]
Nice. Works like a charm. Now I can finally control my Acer monitor! 

BTW. Not a biggie, but the release wasn't signed with a developer ID. Gives the 'ol "can’t be opened because Apple cannot check it for malicious software" message.

**Comment by edeis53** [comment]
and thank you!

**Comment by JoniVR** [comment]
> BTW. Not a biggie, but the release wasn't signed with a developer ID. Gives the 'ol "can’t be opened because Apple cannot check it for malicious software" message.

Thanks for letting me know, I think I forgot to notarize because I did sign it. I'll look into it later.

**Comment by JoniVR** [comment]
Should be fixed now :)
