### ISSUE TITLE
Immediate crash on Macbook pro 10.14.6

### ISSUE THREAD

**Issue by nedelec** [the0neyouseek/MonitorControl#125]
My mac immediately freezes when I start Monitor Control 1.7.0, forcing me to reboot.
It was working fine before I updated to Mojave.
Sorry but I am not sure what is going on or how to find out...

**Comment by JoniVR** [comment]
What Monitor, GPU and cable are you using?

**Comment by nedelec** [comment]
NVIDIA GeForce GT 750M:

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v4

  Displays:
DELL U2412M:
  Resolution:	1920 x 1200 (WUXGA - Widescreen Ultra eXtended Graphics Array)
  UI Looks like:	1920 x 1200
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Display Serial Number:	Y1H5T29I1H1L
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort

**Comment by JoniVR** [comment]
Thanks for the detailed info! 
Can you confirm that it did work on 1.6.0 or other versions?

**Comment by nedelec** [comment]
I believe that MonitorControl 1.6.0 on the same system also crashed. 
but it worked back in July, before I upgraded to Mojave.

**Comment by JoniVR** [comment]
Might be related to your Nvidia card then. My guess would be that the `minReplyDelay` is too high but I could be wrong, we'll need to look into this.

Your system freezes completely right? Like no mouse cursor movement either?

**Comment by nedelec** [comment]
Yes, complete freeze, including the mouse, and I see nothing in the logs.

**Comment by JoniVR** [comment]
My guess is that the issue explained in [this forum post](https://www.tonymacx86.com/threads/controlling-your-monitor-with-osx-ddc-panel.90077/post-581242) is what’s happening:
> The biggest issue is NVidia seems to interpret minReplyDelay differently; where a value of 30 * kMillisecondScale is appropriate for ATI/AMD and doesn't require running the same request several times, 30 is a more appropriate value for NVidia, and 0 still returns a garbage response. If true, this means that DDC Panel never actually KPed an NVidia machine, the kernel was simply waiting 1000 * 1000 times longer for the DDC/CI reply.
Timing is very important for I2C buses as I've been reading, so a "good" value here is critical. If the reply is taken too early, the data will be garbage and fail to checksum, too long and it may mimic a Kernel Panic. Running several successful requests in series is the only real test. Feel free to try different values and report back.
I've also started polishing the app, removing unnecessary entries, and following code guidelines.

So we’d have to play around with a shorter delay and give you a test build to see if that fixes it. 

You could also test this yourself using [kfix/ddcctl](https://github.com/kfix/ddcctl).

**Comment by nedelec** [comment]
Hello, 'ddcctl' does not crash, and detect the monitor, but the brightness does not change. Is there something you would like me to try?

mac:ddcctl-master$ ./ddcctl -d 1 -b 1
D: NSScreen #724053908 (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: Y1H5T29I1H1L
I: got edid.name: DELL U2412M
D: action: b: 1
D: setting VCP control #16 => 1

mac:ddcctl-master$ ./ddcctl -d 1 -b 100
D: NSScreen #724053908 (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: Y1H5T29I1H1L
I: got edid.name: DELL U2412M
D: action: b: 100
D: setting VCP control #16 => 100

**Comment by JoniVR** [comment]
Yes, please test changing volume too as brightness is less prone to causing issues than volume. :)

**Comment by nedelec** [comment]
It did not crash, but this monitor has no speakers, as far as I know. 

mac:ddcctl-master$ ./ddcctl -d 1 -v 10
D: NSScreen #724053908 (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: Y1H5T29I1H1L
I: got edid.name: DELL U2412M
D: action: v: 10
D: setting VCP control #98 => 10

**Comment by JoniVR** [comment]
Hmm might be difficult to debug.. could you try a few of the previous versions and let me know if any of them work? Make sure to test 1.4.0

**Comment by SongHoang** [comment]
I had this issue on a 650M and same Dell U2412M monitor on 2.0.0 I can confirm 1.4.0 works.

**Comment by JoniVR** [comment]
I'm going to close this one as we will continue tracking this issue in #193
