### ISSUE TITLE
Values for DDC audioMuteScreenBlank command are being saved to audioSpeakerVolume

### ISSUE THREAD

**Issue by scorpiondev** [the0neyouseek/MonitorControl#130]
While making performance enhancements, I noticed that when the values for the audioMuteScreenBlank command are successfully read, they are being persisted to the preference values for audioSpeakerVolume instead.

This issue is present as of 6beb9d228e6187bcce69c68f3871d961cbcf7125.

**Comment by JoniVR** [comment]
Thanks for the fix! 👍
