### ISSUE TITLE
Unable to install app "Apple cannot check for malware"

### ISSUE THREAD

**Issue by pawel221** [the0neyouseek/MonitorControl#139]
When I try to open file MonitorControl.1.7.0.dmg I get following message, which basically says:

> The "MonitorControl.1.7.0.dmg" application could not be opened; Apple cannot check for malware.
> This software must be upgraded. Contact the developer for more information.

Tested on MacBook Pro (15-inch, 2019), macOS Mojave 10.14.5 (18F203)

![Zrzut ekranu 2019-10-8 o 16 41 18](https://user-images.githubusercontent.com/956899/66405522-88e77500-e9ea-11e9-97f4-a8ffb53300b1.png)

**Comment by JoniVR** [comment]
Can you try downloading again and trying again? I forgot to notarize when I first released it but fixed it soon after. I checked the dmg and should be signed and notarized.

**Comment by JoniVR** [comment]
Closing due to no response.. feel free to reopen.
