### ISSUE TITLE
Mouse and keyboard stops working

### ISSUE THREAD

**Issue by Perkka2** [the0neyouseek/MonitorControl#140]
When the application is started my mouse and keyboard stops working.
It can be solved by unhooking the monitor and using the built in macbook pro monitor, as soon the monitor is reconnected mouse and keyboard wont react to anything except caps lock again.

I believe it's the same as the issue "freezed my hackitosh right from the start. Restart required to get back. #105"

My external monitor is a DELL UD2717D

**Comment by JoniVR** [comment]
More info would be nice, what macOS, what GPU, what cable, ... also, maybe try [ddcctl](https://github.com/kfix/ddcctl) and report back if you have the same issue or not.
