### ISSUE TITLE
Could I customize shotcut for Hackintosh?

### ISSUE THREAD

**Issue by JasonQS** [the0neyouseek/MonitorControl#142]
the default key bind is F14 for dec and F15 for inc light, is there a way to customize? thanks

**Comment by JoniVR** [comment]
Not as of yet, but it's a feature that we could add in the future. If anyone wants to take a look at it, Pull Requests are always welcome :)

**Comment by KAMIKAZEUA** [comment]
Same as I described https://github.com/the0neyouseek/MonitorControl/issues/118
Yes, setting any key would be really cool.

**Comment by JoniVR** [comment]
I had overlooked that one, will close this issue as it's a duplicate 🙂
