### ISSUE TITLE
M2 Mac mini, the screen becomes blurred and indistinct when connected via HDMI

### ISSUE THREAD

**Issue by nanqic** [the0neyouseek/MonitorControl#1437]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

M2 Mac mini ，the screen becomes blurred and indistinct, My monitor is HP 24w, which support DDC/CI.

### Steps to reproduce

This bug happens twice:
1. I turn the light max use mouse,
2.  I up/down light use keyboard.

### Expected behavior

Hope this won't happen, I restart mac twice.

### Anything else?

Thanks for every developer!

### Environment Information (please complete the following information)

```markdown
- macOS version: latest(13.5.2 (22G91))
- Mac model: Mac mini 2023
- MonitorControl version: latest
- Monitor(s): HP 24w
- Apple Silicon/M1 (yes or no): yes
```

**Comment by nanqic** [comment]
![61695693305_ pic](https://github.com/MonitorControl/MonitorControl/assets/34978586/c5314b9d-3753-43d7-8f6e-5e2cc44c9e36)
I won't use it before the bug fix. Monitor blurred and no signal , I force restart my Mac four times.

**Comment by waydabber** [comment]
MonitorControl does not support the HDMI port of the M1/M2 (entry level) Mini as explained under Compatibility. Use the USB-C instead please! :)

**Comment by waydabber** [comment]
...or for HDMI support you can use the other app, [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme) instead.

**Comment by nanqic** [comment]
All right，thank you for your reply！
