### ISSUE TITLE
Function keys as standard turned off but they don't work

### ISSUE THREAD

**Issue by divdax** [the0neyouseek/MonitorControl#1457]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I installed this app. It didn't work so i deleted it. After that my setting for the functional keys in mac os doesn't work anymore.

    Turn on "Use F1, F2, etc. keys as standard function keys".

I only can access my media keys with "fn" even when the option in the settings of mac os is disabled.
What i can do to disable my functional keys as default?

**Comment by waydabber** [comment]
Honestly, I am not sure why this is happening as the app does not interfere with this setting at all, not while installed or after it is uninstalled. I'll move it to discussions, maybe somebody experienced something similar and might have an insight.
