### ISSUE TITLE
Italian translation missing in 1.7 dmg package

### ISSUE THREAD

**Issue by picov** [the0neyouseek/MonitorControl#146]
The Italian translation added with v 1.7 is present into the source code but not in binary .dmg release.

**Comment by JoniVR** [comment]
As far as I can tell I think they didn't get referenced to the project in the PR, so that's probably why. Thanks for letting us know.

**Comment by picov** [comment]
Please also note that the strings related to the new advanced panel available in v1.7 are missing inside the en.lproj thus is difficult to complete the translation.
