### ISSUE TITLE
No mute when turning sound all the way down on Lenovo X1 (2nd Gen) monitor

### ISSUE THREAD

**Issue by ricardo-fonseca** [the0neyouseek/MonitorControl#149]
Hi

The sound control is not working properly on on Lenovo X1 (2nd Gen) monitor (This may be a duplicate of #94). I'm running version 1.7.0 (build 573)

Two things happen:

1. The mute button has no effect on sound level
2. Lowering the sound all the way down brings the monitor sound down to level 3 or 4 (out of 100), which still outputs sound.

I'd be happy to help with any testing.

Thanks for a great app,
Ricardo

**Comment by JoniVR** [comment]
Hi @ricardo-fonseca!

Both of these issues should have been resolved in #116 and will be added in the next release (which should be soonish) 🙂

**Comment by ricardo-fonseca** [comment]
Thanks a lot.

All the best,
Ricardo

—
Ricardo Fonseca

Full Professor | Professor Catedrático
DCTI - Dep. Ciências e Tecnologias da Informação
ISCTE - Instituto Universitário de Lisboa
Av. Forças Armadas
1649-026 Lisboa
Portugal

tel: +351 21 7650544    ext: 220107
web: https://ciencia.iscte-iul.pt/rpafa/en

On 12 Nov 2019, at 12:05, Joni Van Roost <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ricardo-fonseca<https://github.com/ricardo-fonseca>!

Both of these issues should have been resolved in #116<https://github.com/the0neyouseek/MonitorControl/pull/116> and will be added in the next release (which should be soonish) 🙂

**Comment by JoniVR** [comment]
Hi

Just letting you know that v1.7.1 has been released, please let me know if you happen to run into any issues.

**Comment by ricardo-fonseca** [comment]
It’s working fine, thanks again for a great piece of software!

—
Ricardo Fonseca

Full Professor | Professor Catedrático
DCTI - Dep. Ciências e Tecnologias da Informação
ISCTE - Instituto Universitário de Lisboa
Av. Forças Armadas
1649-026 Lisboa
Portugal

tel: +351 21 7650544    ext: 220107
web: https://ciencia.iscte-iul.pt/rpafa/en

On 13 Nov 2019, at 13:21, Joni Van Roost <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Just letting you know that v1.7.1 has been released, please let me know if you happen to run into any issues.
