### ISSUE TITLE
Audio source change

### ISSUE THREAD

**Issue by funbben** [the0neyouseek/MonitorControl#15]
Feature request : 
My monitor has monitor (iiyama B2791QSU-B1) has built-in speaker, and I would like to easily change the audio source.

Here is the the use case : I use display from HDMI source, and listen to some music or video.
but sometimes I use audio from line-in during my hands-free calls.
=> It would be nice to have an easy way to change the source.

**Comment by the0neyouseek** [comment]
Hi @funbben ,

I understand completely, It was something I wanted to do in the next version.

My goal is to have the app automatically detect the audio source, and if it's anything else other than monitor audio, let the system handle it. 

What you can do right now is open the app Preference window and change the key settings to only listen for Brightness but it's a bit of a pain if you change audio source regularly. 

Anyway, it's in the pipe for `1.3`,
Have a nice day

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
