### ISSUE TITLE
Not working on Catalina anymore

### ISSUE THREAD

**Issue by Moehrenbaum** [the0neyouseek/MonitorControl#150]
First off, thanks for this awesome piece of software. I love it. 

It worked just fine until I updated to Catalina. Now, I continue to get the message:

"MonitorControl" would like to control this computer using accessibility features ....
Grant access...

I did multiple times. It appears in the list, yet nothing is happening anymore. Not sure what else I could provide to help fix this issue. Please let me know and I'm more then happy to check into any logs.

I use a SAMSUNG LC34F791WQUXEN monitor.

Thanks

**Comment by JoniVR** [comment]
Hi! 

Have you tried removing it from the list and then relaunching it? That used to help when people had issues on Mojave. 

I'm personally still running Mojave but once my new 16" arrives I'll be forced to use Catalina anyways so I can look into Catalina specific issues.

**Comment by Moehrenbaum** [comment]
Just tried. The message is not coming up anymore but the keys or menu isn't working either. sorry.

**Comment by JoniVR** [comment]
Hi, I just wanted to let you know that everything still works fine on my new machine running Catalina, so I doubt that is the issue.. Can you try reinstalling or perhaps try a few previous versions?

**Comment by Moehrenbaum** [comment]
Hi there! Thanks for the mail. I appreciate you reaching out. However, I have tried any possible combination (install, uninstall, w/ boot, w/o boot….). It’s not working for me. Anything I can provide for you to test, please let me know.
Best, Dirk

On Nov 30, 2019, at 20:55, Joni Van Roost <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I just wanted to let you know that everything still works fine on my new machine running Catalina, so I doubt that is the issue.. Can you try reinstalling or perhaps try a few previous versions?

**Comment by JoniVR** [comment]
This issue is probably related to #169, I'm going to close this one and use that one for tracking this.
