### ISSUE TITLE
Smaller increments don't work for brightness

### ISSUE THREAD

**Issue by Eric1200** [the0neyouseek/MonitorControl#151]
When using a standard mac display, it is possible to fine tune the brightness and sound volume with smaller increments (1/4 of an increment) when pressing SHIFT+OPTION + the volume or brightness keys.
https://lifehacker.com/adjust-os-xs-volume-in-smaller-increments-by-pressing-o-5916372

Is it possible to add this feature in the next release?

**Comment by JoniVR** [comment]
As far as I'm aware this already works for volume.. but it doesn't seem to be working for brightness at the moment.

**Comment by Eric1200** [comment]
Exactly, it works for volume (at least as I can assume, since I am not
using the setting through MonitorControl) and macOS has the same behavior
for brightness. I must say that I would find it great if I could adjust
more precisely the brightness of my monitor (especially in the lowest
range), as I would have done with a laptop. Nice to have, but I hoped it
would not be a difficulty to implement in the next version.

Éric.


Le mar. 19 nov. 2019 à 17:11, Joni Van Roost <notifications@github.com> a
écrit :

**Comment by scorpiondev** [comment]
Seems to be working fine on the latest **master** commit, and released version 1.7.1 (build 574) - I'm on macOS 10.14 though.

@Eric1200, @JoniVR: Are you both on macOS 10.15?

**Comment by Eric1200** [comment]
Yes, I am using macOS 10.15.1 and also Monitor Control version 1.7.1 (build 574). Sound volume works fine with small increments, but not brightness (and my monitor is a LG 27UD88-W connected in USB-C).

**Comment by JoniVR** [comment]
I'm on 10.14.6 (Mojave). Volume small increments work but not on brightness on both on DisplayPort and DisplayPort through GPU. Makes no sense really since the code seems to be the same.. I'll try testing if it actually worked in earlier versions once I can get some more free time.
