### ISSUE TITLE
LG 27UK850 - OSD not hidden

### ISSUE THREAD

**Issue by gaevoc** [the0neyouseek/MonitorControl#157]
Hi,
when controlling the volume level on my LG 27UK850 connected to a Mac mini 2018, the native LG OSD is not hidden and overlaps the MacOS OSD.

Thank you
Gaetano

**Comment by JoniVR** [comment]
https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences#hide-osd

**Comment by gaevoc** [comment]
> https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences#hide-osd
> 
> Also being worked on in #152

Thank you!
