### ISSUE TITLE
Doesnt work with my lg32lf5610

### ISSUE THREAD

**Issue by llyonard** [the0neyouseek/MonitorControl#158]
Hi!
I have used before other software in trial mode like soundsource or soundcontrol without a problem.
But i cant control the volume with this one, neither manually with the slide nor with my keyboard. 
Is it not supported or i miss something? 
Thanks

**Comment by JoniVR** [comment]
Soundsource and soundcontrol work differently, they don't make use of ddc/ci. You could try a different connector but if your monitor doesn't support the ddc/ci spec there's not much we can do unfortunately. See #61
