### ISSUE TITLE
dosn't works with LG 34WK95U

### ISSUE THREAD

**Issue by alexala1** [the0neyouseek/MonitorControl#160]
As in object, the tool don't works with the LG 34WK95U

**Comment by krotuk** [comment]
I  can confirm it. Does not work with the LG 34WK95U-W. MacBook Pro mid 2017 non touch bar is connected via thunderbolt 3.

**Comment by austboston** [comment]
Also confirmed. Trying to adjust brightness on monitor from Mac without success.

**Comment by FabioTacke** [comment]
Same here.

**Comment by JoniVR** [comment]
The LG page says it should support DDC/CI
https://www.lg.com/us/monitors/lg-34WK95U-W-ultrawide-monitor

Maybe check out:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by FabioTacke** [comment]
Thanks for the advice, @JoniVR! I tried the ddcctl tool. It recognizes the LG display but any command fails with "Failed to poll display!". My monitor is connected to my MacBook Pro (2016, 13") via Thunderbolt 3. 
I'm going to try connecting it via HDMI later.

**Comment by WhosNickDoglio** [comment]
Was having this issue but switching from a HDMI cable to a DisplayPort cable fixed it for me. 👍

**Comment by kevinjohncutler** [comment]
It works for me on this monitor (over DisplayPort). The only issue is that the volume OSD is not completely hidden and flickers.

**Comment by JoniVR** [comment]
@kevinjohncutler This is a known issue with 2 current PR's open (although they are inactive). It's also pretty hard (almost impossible) to completely hide the default OSD.

I'm closing the issue here now as there are other tracking issues for this. For anyone else running into it, please refer to the links posted above :)
