### ISSUE TITLE
LG 27UK850 doesn't respond to brightness keys

### ISSUE THREAD

**Issue by andrekolmeijer** [the0neyouseek/MonitorControl#162]
Hi,

I installed your app and the menubar-icon seems to work fine for adjusting brightness and contrast for my monitor. However, changing the brightness on my MacBook with the keyboard keys doesn't change anything for my monitor. Seems not to listen for keys properly.

I have a:
- MacBook Pro 2016 w/ Touchbar
- LG 27UK850 4K HDR display connected through Thunderbolt 3 (USB-C type)
- External wireless Magic Keyboard & Trackpad 1st gen.
- MonitorControl.app Version 1.7.1 (Build 574)
- MacOS Catalina Version 10.15.2

Note: doesn't respond to either the Touchbar or the Magic Keyboard keys.

Tried removing MonitorControl from System Pref. -> Privacy -> Accessibility and manually adding it again. Reinstalled the app completely. Did a pram- and SMC-reset. No luck so far.

It's a shame, 'cause I was really happy I found your app! At first thought it was only supposed to work with external monitors, but it's supposed to work with the builtin display as well right? Any suggestions to what I can do / try?

Best regards,

André Kolmeijer

**Comment by andrekolmeijer** [comment]
**Update**

Just found out that manually going with my mouse cursor to my external monitor's desktop (Finder) and clicking on the desktop, makes it possible to adjust brightness & volume for my external monitor. 

_Interestingly enough I can change Brightness from the touchbar, not volume though. Can change volume with my Magic Keyboard._

Still doesn't adjust both displays at the same time however, even though I have "Change B/V for all screens" checked. 

Plus it isn't really useful, since I can't cmd + tab into my external monitors Finder. I'd have to cmd + tab to an application open on the monitor and then manually click / slide to my monitor's desktop. For brightness I'd be able to live with that, volume however needs to be mutable instantly.

Since I'm only able to change both B&V with my Magic Keyboard, I'm guessing the problem has something to do with the touchbar. Could explain why both displays aren't adjusted at the same time. Weird though that brightness is adjustable from the touchbar, whereas the volume-keys are greyed out.

Hope the info helps.

**Comment by jasonshelby** [comment]
I have same issue on my LG 27UK650 4K, but it is used to work well when I first install it

**Comment by jasonshelby** [comment]
I fix it !!!  only change another HDML-typec line

**Comment by JoniVR** [comment]
@andrekolmeijer It is how it currently works.. once #148 is implemented, it should be easier to control the internal display but it requires some refactoring of the code. I'm hoping to be able to allow people to control both internal and external at the same time after the rewrite too but currently it's not supported.
