### ISSUE TITLE
Issues with DELL U3419W

### ISSUE THREAD

**Issue by funkyboy** [the0neyouseek/MonitorControl#163]
This is funny.

Everything works as expected when the monitor is connected to an old Mac mini, which has a mini display port.
Nothing works when the same monitor is connected to a Mac Book Pro (13-inch, 2018, Four Thunderbolt 3 Ports) via any of the thunderbolt ports. 
Nothing works = the UI shows the progress bars for both brightness and volume but neither brightness nor volume values actually change (neither using the keyboard shortcuts, nor using the sliders in the menu bar app).

In both cases I am using the same HDMI port. Both machines run macOS 10.14.6.

Happy to provide more details if needed. If you have an idea of how I could start investigating this, please let me know.

**Comment by JoniVR** [comment]
First thing you should definitely try in this case is a different cable when possible. You could be unlucky and have an unsupported display but in quite a lot of cases HDMI doesn't work while something like displayport does.

**Comment by funkyboy** [comment]
Thanks for your help. I ended up returning the monitor because it didn’t fit my needs :(
