### ISSUE TITLE
how to uninstall properly??

### ISSUE THREAD

**Issue by gonzalohp96** [the0neyouseek/MonitorControl#165]
Hi, i would like to know which the process for a clear uninstall? I delete the accessibility permission i give to app and then using appcleaner i delete the app and related files. Is that enough?

**Comment by JoniVR** [comment]
I'm not sure what exactly appcleaner uninstalls, but there's usually also a preferences file. You should be able to find it when you enter the following in terminal:
```sh
ls ~/Library/Preferences | grep "MonitorControl"
```

If you see anything (MonitorControl related) there as a result, run:
```sh
rm ~/Library/Preferences/me.guillaumeb.MonitorControl.plist
```
