### ISSUE TITLE
Display settings resets after sleep

### ISSUE THREAD

**Issue by nekrasovdmitriy** [the0neyouseek/MonitorControl#17]
All application setting are set to zero after waking up from sleep, but displays keep last setting.

![GitHub Logo](https://i.imgur.com/62GriVC.jpg)

**Comment by the0neyouseek** [comment]
Hi @nekrasovdmitriy,

Thanks for the report, can you tell me which settings are reset exactly ? The ones in the app preferences ? The value of the contrast/brightness/volume levels of displays ? Both ?

**Comment by nekrasovdmitriy** [comment]
The value of the contrast/brightness/volume levels of displays.

**Comment by the0neyouseek** [comment]
Hi @nekrasovdmitriy,

I think I've track down this bug to the fact that your monitor may not support to read `ddctl` command values.  
Does this also happen when you first launch the app or only after waking from sleep ?

If it's this, what I'll do is test if the monitor support read command and if not, set the slider value to the last value saved.  
Though, it has a kind of drawback, meaning that if you manually change brightness, contrast or volume on your display when the app isn't launched, the sliders will not reflect these changes, and have the wrong values.

**Comment by funbben** [comment]
I have the same behavior, when first launching the app, all sliders are set to 0%
(My monitor is a iiyama B2791QSU-B1)

**Comment by falcn** [comment]
P2715Q does not support ddc read, so yeah, everything is at zero after waking up from sleep. It makes sense to set sliders to last used values instead.

**Comment by falcn** [comment]
1.3.0 become worse in that regard. After waking app, sliders are laggy, and do nothing. App has to be restarted to restore its function.

**Comment by falcn** [comment]
Any chance to get it fixed in the next release? I have to restart MonitorControl every time I wake up my macbook, otherwise it hogs CPU and not responding to input. Looks like it is stuck in the ddcctl read loop (Dell P2715Q does not support ddc read)

**Comment by the0neyouseek** [comment]
Is this still an issue for you @falcn ?

**Comment by JoniVR** [comment]
This is most probably due to your display not being able to read the values using ddc.

I have the same issue, currently the app already falls back to last known values though and when #97 gets merged and released you'll be able to disable polling altogether so you don't get the CPU hog.

Going to consider this closed due to inactivity and partial fix should already be there. 
Feel free to reopen if I missed something here.
