### ISSUE TITLE
Can't remove from MacOS "Login Items"

### ISSUE THREAD

**Issue by mblumberg** [the0neyouseek/MonitorControl#179]
I specified to add MonitorControl to "Login Items" when installing the app.  Now I want to remove it (because it does not work: Seems I have the same issue as reported in https://github.com/the0neyouseek/MonitorControl/issues/61).  But: 

[1] When I got to System Preferences > Users & Groups > Login Items, MonitorControl is not listed
[2] Nevertheless, when I reboot, MonitorControl does auto-launch.

Any advice how to prevent this app from auto-launching?

**Comment by JoniVR** [comment]
Have you tried checking/unchecking `Start MonitorControl at login`? in General settings?
![image](https://user-images.githubusercontent.com/7591717/75142947-6ed9d500-56f4-11ea-9db8-bc6350dea4ec.png)

**Comment by mblumberg** [comment]
Thanks.  That worked: the app no longer launches at login.
 
Can you clarify why this does not work as expected?  (e.g. When I click in the app UI to set it to "Start at Login", it does not appear in the System Preferences "Login Items" list.)

**Comment by JoniVR** [comment]
I honestly have no idea.. my guess is that there are multiple ways to set items as login items and they're not consistent. 

I think the login items are a way for you to set specific apps to launch at startup yourself, although we might be able to set it there too, not sure. 

You also have, for example, `/Library/LaunchDemons/` and `/Library/LaunchAgents' who also manage startup items that won't show up in that list.

**Comment by mblumberg** [comment]
Thanks --
