### ISSUE TITLE
Brightness keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by funbben** [the0neyouseek/MonitorControl#18]
It was working fine in 1.1  I could dim brightness on mac internal display, and external displ, but it doesn't work in 1.2.

**Comment by the0neyouseek** [comment]
Hi @funbben ,

Yeah I just noticed that too, I'll try to fix it this week-end.

**Comment by drewlustro** [comment]
@the0neyouseek - I know this is off-topic, but I just wanted to thank you for forking the original code of this app and maintaining a functional replacement. I had no idea that DCC/CI comm was possible on macOS.

**Cheers** 🍻

**Comment by the0neyouseek** [comment]
Hi everyone and thanks for the kind message @drewlustro,

I've uploaded a `v1.2.1` which should hopefully fix this, tell me if it works for you all.

Have a nice day

**Comment by funbben** [comment]
It still don't work, so for the moment I stay with 1.1 that works fine for shortcut
