### ISSUE TITLE
iMac as 2nd Monitor didn't work

### ISSUE THREAD

**Issue by electricarts** [the0neyouseek/MonitorControl#185]
I use an old iMac as a second monitor on my 5K iMac (Thunderbold 3 -> Mini Display Port). With this it seems not to work. Changes in the menulet are ignored.

**Comment by kumowoon1025** [comment]
If the display works that means you're using a AV output adapter, and not the Apple TB3-TB2 adapter right? If the app works using the adapter on a different display, that probably means the iMac in TDM doesn't support DDC. It could be the adapter though. Do you get sound over mDP with this setup?

**Comment by JoniVR** [comment]
I'm going to point you to the Monitor troubleshooting guide for this:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

Feel free to post your setup in #82 after trying the troubleshooting, we're trying to avoid issues for each specific display as that clutters the issue list quite a bit.
