### ISSUE TITLE
Mi Monitor 34‘  Brightness ok✅，Volume Not ok❌

### ISSUE THREAD

**Issue by black-snowflake** [the0neyouseek/MonitorControl#196]
Brightness ok
Volume Not ok

PIDVID：0x61A9  0x3444

**Comment by black-snowflake** [comment]
DP 1.4  
RX 5700xt

**Comment by JoniVR** [comment]
See https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by JuanIrache** [comment]
Did you find a solution for this? Thanks

**Comment by black-snowflake** [comment]
No.   It could be a monitor firmware problem

Juan Irache ***@***.***> 于2021年9月6日周一 上午6:07写道：
