### ISSUE TITLE
is there a way to reset the settings back to default?

### ISSUE THREAD

**Issue by abmicyau** [the0neyouseek/MonitorControl#20]
I may have messed up the contrast and I'm not sure how it was before..

**Comment by the0neyouseek** [comment]
Hi @abmicyau ,

I'm sorry but there's no such setting in the app but you can do it in you monitor osd by reseting to "factory settings". 
If you want to keep you current settings I'ld suggest you set the contrast value to something between 50 to 75%, in my experience, those values works pretty well for most monitors.

**Comment by abmicyau** [comment]
okay, thanks for your help! :)
