### ISSUE TITLE
Two Monitors but only one works

### ISSUE THREAD

**Issue by Mibra-de** [the0neyouseek/MonitorControl#215]
Hallo, i have two Samsung U32R592 both of them on a MacMini over Tunderbolt to Displayport. One of them are controllable the other one dosn´t work. Each monitor on its own works fine. Any ideas?

**Comment by lucguerraz** [comment]
I have two Asus Monitors, same make and model. And I have this issue too. Thanks for any help

**Comment by bottlebug** [comment]
I have the same issue with my 2 LG displays. Both connected via HDMI to USB-C adapters.

**Comment by JoniVR** [comment]
Duplicate of #49
