### ISSUE TITLE
Monitor volume jumps in steps of 6

### ISSUE THREAD

**Issue by parkerjm** [the0neyouseek/MonitorControl#221]
On an LG 42" 4K monitor using DP over USB-C. Volume and brightness controls work great, but I notice that the volume jumps in steps of 6 exclusively. If I manually set the volume to 8 and increase, it jumps to 12. If I decrease, it goes to 6. etc, etc. Is there any way to get finer-grained control?

**Comment by parkerjm** [comment]
Solved: holding option + shift and then using my keyboard's volume knob results in steps of 1 instead of 6.

**Comment by cryptosteve2** [comment]
this should be documented as I have the same question today. A configurable option would be nice also.

**Comment by parkerjm** [comment]
this is a core MacOS thing, not part of this app, don't know how much control over it the app could have.
