### ISSUE TITLE
F1 and F2 become overridden when MonitorControl is running

### ISSUE THREAD

**Issue by Amir-Hass** [the0neyouseek/MonitorControl#23]
Hello,
Thank you for your continued development of the program. I like that I can finally edit both monitor's brightness at the same time correctly. However, when MonitorControl is running, I cannot click F1/F2 on my keyboard although in Karabenier-Elements I have it set to use the F1, F2, etc. keys as standard function keys. I have the tilde (`) key on my keyboard set to enable the function key as I do not have a physical one. Not sure if this is something that can be solved through MonitorControl or Karabenier. However, the issue does go away after quitting MonitorControl, although of course I lose the ability to easily control the brightness.

**Comment by the0neyouseek** [comment]
Hi @Amir-Hass ,

Right now this is intended behavior as the app listen for keys event on their keycodes directly and these are hardcoded. I will however look for a way to listen only when the `fn` (or whatever key you set as replacement) is pressed (and the other way around if you have enabled the setting `Use F1, F2, etc. keys as standard function keys`). 

This should solve your issue 😄

**Comment by reitermarkus** [comment]
This is exactly the issue which https://github.com/the0neyouseek/MediaKeyTap/pull/1 should fix.

**Comment by reitermarkus** [comment]
This was fixed in https://github.com/the0neyouseek/MonitorControl/pull/29. @the0neyouseek, would be great if you could create a new release with it.

**Comment by reitermarkus** [comment]
@the0neyouseek, ping.

**Comment by gxfxyz** [comment]
Hi @the0neyouseek, the latest release v1.3.0 still overrides F1 and F2. Would really appreciate a new release with the fix #29. Thank you.

**Comment by wmertens** [comment]
@the0neyouseek 	I'm trying to build master to have this fix, but I can't figure out how to get around the code signing :-( could you please make a build for this? Many thanks ❤️

**Comment by kostya-666** [comment]
@the0neyouseek this was merged in master one year ago. Please make new build with it to celebrate ))

**Comment by kostya-666** [comment]
https://github.com/JoniVR/MonitorControl/releases/tag/1.3.1 fork build includes fix and works for me

**Comment by reitermarkus** [comment]
Should be fixed in the latest release.
