### ISSUE TITLE
v1.30 keyboard control works intermittently on some displays

### ISSUE THREAD

**Issue by waydabber** [the0neyouseek/MonitorControl#24]
v1.30 - Keyboard control seems to be working as far as the bezel notification (system brightness overlay) is displayed properly. However the actual Brightness is usually not changed or the changes are applied only intermittently. I have to long press F1 decreasing the brightness all the way down, then it eventually dims the display, or I have to long press F2 to increase brightness all the way up and it eventually brightens the display - or sometimes the changes are applied halfway, but not always. Single keystrokes almost never work. The manual slider seems to work but is a bit more choppier than the previous version.

v1.21 - Brightness control is silky smooth.

EDIT: the issue in v1.30 seems to be display specific. Brightness level control is semi broken on my LG 27UD88 4K display (+macbook 2017) but works properly on my Lenovo L24Q display (+mac mini 2012).

EDIT2: only a hunch: @reitermarkus said _"I added a loop which tries more often to get the values from the display, since for me the default value of 10 tries in ddcctl does not work reliably. For me, the average is at about 200 tries, and can be up to 600 tries"_. The difference between the 27UD88 and L24Q is that _ddcctl_ is unable to read values from the 27UD88 (this might be a bug in _ddcctl_ itself, since LG's own DDC/CI control app for MacOS reads the settings just fine - or LG displays might have a nonstandard DDC/CI implementation). The choppiness might be related to the increase in the "tries"? I did not examine the code so it's only a guess on my behalf.

**Comment by reitermarkus** [comment]
The loop I added is only used when getting the values, not when setting them, so it shouldn't have any effect on the controls.

**Comment by the0neyouseek** [comment]
Hi @waydabber ,

Thanks for the report, I'll look into it asap and edit this answer when I know more.

**Comment by waydabber** [comment]
@reitermarkus, thanks for the clarification.

Just to be sure, I tried v1.30 on a differenct Mac and another LG display (an 27UD58B this time), I experienced the same issue. v1.21 is fine.

**Comment by the0neyouseek** [comment]
Closing, please see #82
