### ISSUE TITLE
Works on Dell P2715Q but not on LG IPS277

### ISSUE THREAD

**Issue by techo91** [the0neyouseek/MonitorControl#25]
Hi,
Thank you for the great app, but a have an issue with the LG IPS277-L display. The Dell P2715Q display connected via DisplayPort works perfectly, but I can't control the brightness of the LG one (connected via HDMI). Is there anything I can do to make that one work?

**Comment by the0neyouseek** [comment]
Hi @techo91,

As this app depends on [kfix/ddcctl](https://github.com/kfix/ddcctl) for controlling external display, it may simply be that the LG IPS277-L does not support DDC.

You should ask your question there for support,
Have a nice day

**Comment by techo91** [comment]
According to LG It does. That is the reason I asked. Thank you.
