### ISSUE TITLE
Dim all monitors

### ISSUE THREAD

**Issue by funbben** [the0neyouseek/MonitorControl#28]
It would be nice to be able to dim all monitors when dimming one screen
(It could be set as an option)

**Comment by funbben** [comment]
Well, I just noticed that there already is an option for that, however the mac built-in display doesn't dim brightness when using monitor control

**Comment by the0neyouseek** [comment]
Hi @funbben,

This is a duplicate of #14 😄 
I'm closing this, If you want to further discuss this issue, please go and post a message there.

Have a nice day.
