### ISSUE TITLE
Brightness works but no volume control? (U28E590)

### ISSUE THREAD

**Issue by CedFlanders** [the0neyouseek/MonitorControl#33]
Hi, 

First of all thank you so much for making this program, I never thought it would be possible to change brightness on a non apple or ultrafine monitor.

On my U28E590, changing the brightness works like a charm, but the volume never changes, I can change the sliders or use the volume keys and I will see the overlays but the actual volume on the speakers which are connected to my monitor remains unaffected. 

Samsung U28E590 connected to a 2015 rMB via an USB-C to displayport cable.  

Perhaps somebody here has an idea what could be causing this, in any case I love the program for the brightness controls already.

**Comment by the0neyouseek** [comment]
Hi @CedFlanders,

First of all, thank you for your kind words. Sadly I can't help you with this issue as it involves the library used to control the monitor [https://github.com/kfix/ddcctl](https://github.com/kfix/ddcctl).
Sadly, your monitor may not support all the options of `DDCCTL` including volume control and this may be the reason your seeing this.  
But please do try using the library directly (in command line) to control the monitor volume and if it works I'll be sure to take a second look at this.

Have a nice day.
