### ISSUE TITLE
Allow controlling brightness and volume with smaller increments from keyboard

### ISSUE THREAD

**Issue by cvachon-akivo** [the0neyouseek/MonitorControl#35]
Problem: volume and brightness increments are too big on some monitor.

Please consider adding a preference to allow the user to define the increments for volume and brightness control, when using the keyboard. A integer value on between 1 and 10 would be great.

**Comment by the0neyouseek** [comment]
Hi @cvachon-akivo,

I was thinking of adding something like Shift <kbd>⇧</kbd> + Option <kbd>alt</kbd> + <kbd>F1</kbd>/<kbd>F2</kbd> to have smaller increments like on a real mac.

I'll keep this issue open and notify you when this is implemented.

Thanks, have a nice day.

**Comment by cvachon-akivo** [comment]
Hi Guillaume,

That would be perfect👌. 

Thank you for your great work on this clever little app!

Best,

Christian

**Comment by kylemhall** [comment]
I'd also love to see small increments for volume control. I would be nice to be able to specify the increment size in the app preferences. Thanks for the awesome app!

**Comment by remus-b** [comment]
I was looking for something similar. The increments are too big, and volume changes are harsh.

**Comment by larskochhansen** [comment]
Me2 🙏

**Comment by the0neyouseek** [comment]
Thanks for waiting everyone, should now work with the latest release ([v1.6.0](https://github.com/the0neyouseek/MonitorControl/releases/tag/v1.6.0)) :tada:
