### ISSUE TITLE
Thunderbolt dock and stuttery mouse pointer movement

### ISSUE THREAD

**Issue by brechtm** [the0neyouseek/MonitorControl#36]
After starting MonitorControl, my mouse pointer movement is no longer smooth. Moving a window around is also much less smooth (you could say it's about 10 fps). This is with a Samsung SyncMaster 226BW (DVI) plugged into the HDMI port of a Caldigit Thunderbolt Station 2 and a Mid-2014 15-inch MacBook Pro.

When I directly connect the monitor to my MacBoo, there is no noticeable change in pointer smoothness!

I can control the brightness of my external monitor using Monitor Control in both cases. Also, Activity Monitor shows MonitorControl using around 10% CPU time constantly (with and without dock). I'll open a separate ticket for this.

**Comment by brechtm** [comment]
I also see high CPU usage when the monitor is connected directly to the MacBook (without the Thunderbolt dock). Therefore, I believe these to be two separate issues.

Please only look into this when you feel like it. Open source should be fun :-) I can imagine this one affecting few people and being very tricky to debug.

**Comment by the0neyouseek** [comment]
Closed, please see #37 for further discussions
