### ISSUE TITLE
Where is "Donate" button?

### ISSUE THREAD

**Issue by ifixr** [the0neyouseek/MonitorControl#38]
This little app is so lovely I have just one issue with it: how can I donate a few quid for all your nice work?

**Comment by the0neyouseek** [comment]
Hi @ifixr,

Thank you for kind comment, if you wish to donate directly to me you can do so here on my [Paypal](https://www.paypal.me/broderg).
Or you can donate to support the [French Red Cross](https://soutenir.croix-rouge.fr/don-ponctuel/) here if you prefer.

Have a nice day.
