### ISSUE TITLE
Does Not Work After Waking from Sleep

### ISSUE THREAD

**Issue by methodbox** [the0neyouseek/MonitorControl#40]
The app works great, generally, so thanks!

But if my Mac goes to sleep, once it wakes it no longer sees the monitor as an output source. The media keys will switch to controlling the Mac display and volume itself, rather than the monitor. 

A reset restores functionality.

Removing this app restores that functionality.

I'm on macOS 10.13.5.

My monitor is an LG 32UD89-W.

**Comment by the0neyouseek** [comment]
Hi @methodbox,

Thanks for taking the time to test the app. I'm currently working full time and don't have much free time to develop MonitorControl but I'll try to look this up asap.

Have a nice day.

**Comment by vogtmh** [comment]
I experienced the same issue. I'm pretty sure it's related to too much polling over the DDC, so the monitor just shuts down the input. I removed it in my version, which also reduced cpu usage to nearly 0% 

Try it out, maybe it helps you as well :-) 

https://github.com/mavodev-de/ScreenVolume2

**Comment by methodbox** [comment]
Strangely after switching back to High Sierra after trying out Mojave, this works fine, but I will check it out @vogtmh - thanks!

**Comment by womeimingzi11** [comment]
Same situation for me. But it will go to work after 3-5 minutes when may MacBook Pro 15' 2015 wake from sleeping, during this period, the brightness will go to highest, even the ddcctl command doesn't work. My OS is Mojave 10.13.3

**Comment by sovon** [comment]
@the0neyouseek I've tested and tried everything that's out there and this is the only option that actually works. Thanks for making this tiny but very useful utility.

However if you have time, please take a look into the issue where the touchbar buttons don't work right after boot or right after waking from sleep. It has to get 2-3 minutes of time to start responding. I'm seeing this on Mojave on MBP 13" 2017 connected to LG 27UK850.

Thanks.

**Comment by sovon** [comment]
Also, might I suggest adding a basic equalizer for the sound of the monitor only (not in build laptop speaker). Because most of the times the sound of the monitor is horrible out of the box; at lease it is the case for me.

Having an option to do so would certainly help. Besides there is not even a single app out there to do so.

**Comment by JoniVR** [comment]
> It has to get 2-3 minutes of time to start responding. I'm seeing this on Mojave on MBP 13" 2017 connected to LG 27UK850.

I'm pretty sure this is an issue related to #37. High polling in previous versions prevented it from working properly while it's polling (because it tried for 100 times). I had the same issue. Currently it's already changed to polling only 10 times and a feature to manually override polling is being worked on in #97

**Comment by brechtm** [comment]
> 
> 
> Also, might I suggest adding a basic equalizer for the sound of the monitor only (not in build laptop speaker). Because most of the times the sound of the monitor is horrible out of the box; at lease it is the case for me.
> 
> Having an option to do so would certainly help. Besides there is not even a single app out there to do so.

Check out [eqMac](https://bitgapp.com/eqmac/).

**Comment by sovon** [comment]
> > Also, might I suggest adding a basic equalizer for the sound of the monitor only (not in build laptop speaker). Because most of the times the sound of the monitor is horrible out of the box; at lease it is the case for me.
> > Having an option to do so would certainly help. Besides there is not even a single app out there to do so.
> 
> Check out [eqMac](https://bitgapp.com/eqmac/).

I use a bluetooth speaker alongside with my airpods & laptops built-in speaker & monitor's speaker - these gets interchanged frequently based on availability & connection. While on an external monitor connected to a macbook in both normal & clamshell mode. Try using that app you suggested for a week. You'll change your opinion. 

I've tried everything that's out there. When it comes to using 'device specific' equalizer, it sucks. nothing works.

**Comment by JoniVR** [comment]
I mean you could try opening an issue for it but I personally am against adding this to MonitorControl. 

This is something you see in lots of open source projects where people keep requesting more and more features that are not really related to the project, the result is usually a bloated codebase and lots of stuff to maintain. (Nothing personal that’s just my experience with it)

I think it would be better to create a separate tool for that. Keep things focussed on the main functionality and create different tools for specific use cases like equalizers. Of course that’s just my opinion on the matter.

Also, as far as I’m aware eqMac is Open Source too so you could just open issues/create pull requests there for things you’d like to see improved?

**Comment by sovon** [comment]
> I mean you could try opening an issue for it but I personally am against adding this to MonitorControl.
> 
> This is something you see in lots of open source projects where people keep requesting more and more features that are not really related to the project, the result is usually a bloated codebase and lots of stuff to maintain. (Nothing personal that’s just my experience with it)
> 
> I think it would be better to create a separate tool for that. Keep things focussed on the main functionality and create different tools for specific use cases like equalizers. Of course that’s just my opinion on the matter.
> 
> Also, as far as I’m aware eqMac is Open Source too so you could just open issues/create pull requests there for things you’d like to see improved?

I agree with what you are saying. Having lots of stuff in tiny utilities like this might slow it down even if by a small amount. I've stopped using my monitors speaker altogether at this point.

Anyways, I'd prefer to see the tool itself become faster. The lag b/w wake up/sleep still remains and I notice is every day. There has probably been some updates since my last installation. Hope it gets fixed.

**Comment by JoniVR** [comment]
> Anyways, I'd prefer to see the tool itself become faster. The lag b/w wake up/sleep still remains and I notice is every day. There has probably been some updates since my last installation. Hope it gets fixed.

Yes, this is being worked on in a current PR. In `v1.5.2` we reduced the default amount polling tries from 100 tries to 10 tries, which should reduce cpu usage at wake/launch already, but in a future release we'll add the advanced settings panel where you can set custom polling settings or disable polling altogether. I'm pretty sure that should fix the issue, if not then we'll keep looking into it.

**Comment by methodbox** [comment]
Adding an EQ to this project isn’t going to be any different than using what has been suggested.

Ultimately, you’re controlling the output from the source (the Mac) to the output (your monitor).

Whether you use eqMac or its integrated here, you’re not going to see any difference, assuming the same functionality - you’re still EQing the same source and outputting to the same output.

**Comment by sovon** [comment]
Been testing the 1.5.2 for a week now. It's a lot of improvement. Specially with initial unresponsiveness. it's gone; at least to the extent of my use case of external monitor. Great. 👌
