### ISSUE TITLE
Hide icon on status bar

### ISSUE THREAD

**Issue by Erik262** [the0neyouseek/MonitorControl#41]
Hey very nice work you have done ! 🥇 
Want to ask, if is possible to hide the icon on the status bar?.
I'm not really a fan about having to much different icons there :)

**Comment by vogtmh** [comment]
You could simply use an app like [Vanilla](https://matthewpalmer.net/vanilla/) to hide all unnessary icons ;-)

**Comment by Erik262** [comment]
Thanks!

**Comment by htpcrig** [comment]
It would be nice to have his feature

**Comment by Vxider** [comment]
Vote for this feature

**Comment by Erik262** [comment]
Yeah this would be great^^

**Comment by norenjr** [comment]
Also vote for it!

**Comment by notrealdev** [comment]
Vote for it, consider integrating it into Monitor please.
