### ISSUE TITLE
After the PC is started, MonitorControl is always at 0

### ISSUE THREAD

**Issue by kocinko** [the0neyouseek/MonitorControl#44]
Hello,
Please help, how to set MonitorControl to volume level ? 
After the PC is started, MonitorControl is always at 0

Thanks

PS: EFI/CLOVER/drivers64UEFI - is OK

**Comment by vogtmh** [comment]
I've experienced the same issue. I guess it's because MonitorControl doesn't read the values on startup. However, it was just a display bug for me, sound worked fine (no muting). Pressing Volume Up / Down got the correct value displayed for me.

**Comment by reitermarkus** [comment]
It should restore the last saved values now.
