### ISSUE TITLE
Image freezes with Dell P2715Q

### ISSUE THREAD

**Issue by ycanales** [the0neyouseek/MonitorControl#45]
I've been using ddcctl to set the brightness of my Dell P2715Q screen from the terminal without problems. However when trying to, for instance, get the brightness value without setting it, the screen freezes (keeps the last image frozen).

The same freezing happens when opening your app (1.3.0)

**Comment by vogtmh** [comment]
I'm having the problem that sometimes the polling for the brightness value just goes crazy, sends too many DDC requests and causes my LG 34UM94C-P.AEU to go into sleep mode. The same happens, if I send too many volume up / down requests in a short period.

**Comment by the0neyouseek** [comment]
Closed, please see #82 for further infos/discussions
