### ISSUE TITLE
Listening for volume doesn't work with non monitor output

### ISSUE THREAD

**Issue by renox92** [the0neyouseek/MonitorControl#48]
If I have "listen for volume" activated I can't use media keys to adjust volume of laptop's internal speakers or wireless headphones. I can still use default macos volume slider to do that. Would be great if for audio the app could check which output device is selected and then decide whether to override volume commands or not.

**Comment by JoniVR** [comment]
I don't think this is very actively maintained, but I've implemented this on my fork:
https://github.com/JoniVR/MonitorControl

**Comment by the0neyouseek** [comment]
Hi. Sorry I haven't been able to maintain this as much as I wanted to with work getting in the way.

Anyway, I was planning on adding support for this but if @JoniVR got it working, maybe you can make a pull request ?

I'll work on this project this week-end and probably publish a new version.

**Comment by JoniVR** [comment]
I can do a separate PR for that if you want to, however, there were some compiling errors that require updates to those third party frameworks (was either MediaKeyTap or MASPreferences).

Anyways, I implemented it on my fork by using the `AMCoreAudio` framework, if you can update the dependencies some time soonish I'll do a PR and implement this feature for you. Also, don't update the ddcctl dependency as it's current version causes a kernel freeze on macs with integrated graphics chips. I think they're working on a fix but might be useful to know not to update that dependency. (see discussion: https://github.com/kfix/ddcctl/pull/42)

**Comment by JoniVR** [comment]
Also, now that I have your attention, my guess is that #37 is related to #21, in commit 9f4e5fb an (in my opinion) unnecessary loop was introduced which slows the program down a lot (especially since ddcctl internally loops over that part of the code 10 times already), I managed to speed everything up and make it stable in my fork by simply removing that loop. The application was pretty unusable for me with it.

**Comment by the0neyouseek** [comment]
Hi @JoniVR and thanks for all the great work and infos.

Yeah I'm pretty sure that's where the problem's coming from too. I thought being in a background thread it wouldn't be that bad when I merged it but I'll reverse it this week-end.

**Comment by JoniVR** [comment]
Yeah, or if you could just update those peer dependencies (except for ddcctl) you forked (MAS and MediaKeyTap), that would be fine by me too, I'll do a PR with some other stuff I improved on my fork including an updated README with more screenshots (if you're up for that). It will probably also be for the weekend or afterwards as I'm currently studying for exams.

**Comment by the0neyouseek** [comment]
I'll do just that then, thanks @JoniVR . I'll be waiting for your PR then.

Good luck with your exams 💪

**Comment by JoniVR** [comment]
Thanks! I've written it down but please do remind me if I haven't submitted a PR by the end of next week because I might forget 😄.

**Comment by reitermarkus** [comment]
This should be fixed now.
