### ISSUE TITLE
Mouse cursor stutters as soon as the app is launched

### ISSUE THREAD

**Issue by 20015jjw** [the0neyouseek/MonitorControl#50]
I downloaded the latest version of the MonitorControl from the release section. As soon as I start the app, the cursor becomes very unresponsive. The app works (at least the brightness does), and the rest of the system is fine, as the youtube video I'm watching doesn't show any signs of lagging or stuttering. 
I might do some digging on my own into this issue, but if you can find out why, it would be awesome. Please let me know if more information for debugging is needed.

**Comment by koriwi** [comment]
Same for me.
(I have a hackintosh laptop with real HDMI and two thunderbolt 3 ports)
When i use a USB-C to HDMI cable i get the stutters.
When i use the real HDMI port it works fine.
Tested this with a MacbookPro 2017 over USB-C and have the same stuttery mess.

**Comment by TheAmenRa** [comment]
Same. Macbook Pro 2018 15 -> USB-C dongle -> HDMI.
It is also doesn't working. I have an LG 34UM95.

**Comment by MHX792** [comment]
Any fix incoming?

**Comment by MHX792** [comment]
I found a way to reproduce the sluggishness. I use two monitors. When both monitors are turned on and I launch Monitor Control the sluggishness goes away after a few seconds. If, however, one monitor is turned off (but still connected) the sluggishness persists. 

I suppose MonitorControl the sluggishness occurs when MonitorControl tries to identify the connected monitors. If a monitor is only turned off, it probably cannot identify it therefore leading to infinite sluggishness.

Further information that may help you find the bug: After launching MonitorControl when both monitors are turned on, the sluggishness goes away quickly. When I turn off the second monitor after that, the sluggishness does not come back. It also works without any problems, when the mac goes to sleep and the first monitor is cut off from power during that.

**Comment by the0neyouseek** [comment]
Hi everyone, thanks for the report and sorry for the delay responding. I'll have a look at fixing this bug this week-end.

**Comment by JoniVR** [comment]
Possibly related to #37

**Comment by the0neyouseek** [comment]
Closed, see #37 for further discussions
