### ISSUE TITLE
Start at Login : MonitorControlHelper keeps crashing

### ISSUE THREAD

**Issue by mrgooge** [the0neyouseek/MonitorControl#53]
Every 10 seconds I get the following in my system log after selecting any option MonitorControl Preferences Keys Listen for  example below:

Oct 23 14:09:35 xxxxxx com.apple.xpc.launchd[1] (me.guillaumeb.MonitorControlHelper[2055]): Service exited with abnormal code: 1
Oct 23 14:09:35 xxxxxx com.apple.xpc.launchd[1] (me.guillaumeb.MonitorControlHelper): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

...and thousands more of the lines above, etc..

**Comment by mrgooge** [comment]
Actually, I reported this wrong... It's not the Preferences/ Keys/ selections that cause the constant Mac system messages..It's when you've selected, Preferences/ General/ Start MonitorControl at Login option. Then the endless respawn messages begin, once I unchecked this, the Mac system log stopped the messages.

**Comment by markovicdenis** [comment]
Same here, crashes after sleep/wake on multi monitor setup. I even used sleep watcher to kill it before sleep and start after wake, but 1 in 10 times it still crashes (detects only one monitor)..

**Comment by reitermarkus** [comment]
This is probably fixed now.
