### ISSUE TITLE
Dell P2415Q Volume Control Support

### ISSUE THREAD

**Issue by maojinbing** [the0neyouseek/MonitorControl#54]
DELL P2415Q DisplayPort  Audio  ？

**Comment by stephenreay** [comment]
I'm seeing what I assume is the same issue. A Dell P2415Q with speakers plugged into the headphone jack, the volume control doesn't affect output volume.

**Comment by stephenreay** [comment]
No, apprently those displays don’t support volume control.

**Comment by the0neyouseek** [comment]
Hi everyone,

This app use this lib : [@kfix/ddcctl](https://github.com/kfix/ddcctl) to control brightness/volume. 

As @stephenreay said, your monitor may only allow certain command to be used but not others, in this case there's nothing more to do sorry.
