### ISSUE TITLE
Not working with ASUS ROG PG384Q

### ISSUE THREAD

**Issue by EvilSquirrel** [the0neyouseek/MonitorControl#55]
The app doesn't seem to work with my PG384Q, has anyone else has success with it? The volume popup shows up but there is no effect whatsoever on the output volume. I don't think it's the monitor itself; volume control works properly from the keyboard using Windows.

**Comment by the0neyouseek** [comment]
Hi @EvilSquirrel sorry for the delay responding.

Did you successfully made it work ?

If not, the app uses this lib [@kfix/ddcctl](https://github.com/kfix/ddcctl) control the monitor. As ddc/ci is a standard poorly implemented by many manufacturer your monitor may simply not be compatible with volume control.
