### ISSUE TITLE
No sound control with Lenovo P-27h-10

### ISSUE THREAD

**Issue by inseltiger** [the0neyouseek/MonitorControl#57]
Although I can control display brightness with the function keys, this does not work for volume control.

The program will detect my input from the keyboard, but not make any changes to the sound output.

Also I would like to change the brightness of all displays (internal + external) together.

Does anyone know the, what the cause of all this is? Apart from this the app is great! Could I make some changes to the source code myself?

**Comment by the0neyouseek** [comment]
Hi @inseltiger and sorry for the delay responding.

For your first question, this app uses a library ([@kfix/ddcctl](https://github.com/kfix/ddcctl)) to control the monitor and the standard used isn't well supported by all manufacturers so you monitor may not support volume control.

Secondly, being able to change both internal and external brightness/volume together is a feature I plan to work on soon, so please stay tuned for a new version. You're of course free to work yourself on the source by forking this project.

Have a nice day
