### ISSUE TITLE
Not working with 2018 Mac mini + Sony X720E via HDMI

### ISSUE THREAD

**Issue by tbird2** [the0neyouseek/MonitorControl#58]
Macs typically cannot control the brightness or volume of an external monitor connected via HDMI. But, that's what I want. It's not clear to me if MonitorControl is supposed to do this or not.

I don't expect MonitorControl to actually control the monitor's brightness or volume settings. I know that's impossible (until some day that HDMI-CEC works). What should be possible today and what I would like is to have it lower the volume or brightness of the signal going to the monitor. So, the monitor would be set to the maximum normal brightness and volume that you would ever want, and then MonitorControl would LOWER the brightness and volume to what you actually want to use now. 

The "Brightness Slider" app in the Mac App Store does this, and it works okay, but it doesn't work with the native brightness function keys. Also, the Soundflower kernel extension together with the SoundflowerBed app can control the volume by lowering the volume output to the monitor. But, it produces a sound delay that makes it awful for watching any video with sound. To me it's completely unusable, but it proves the concept can work, if they could just fix the delay.

It would be great if MonitorControl could do this. If it's supposed to do this, then I wonder why it's not working for me. For me, the MonitorControl menu appears in the menu bar. It shows the name of my monitor at the top of the menu "SONY TV *00" and I can move the sliders and they appear normal like they should do something, but absolutely nothing happens when I change them.

Thanks!

**Comment by the0neyouseek** [comment]
Hi @tbird2 and sorry for the slow response.

Firstly, controlling the brightness and volume of external (non-apple/lg ultrafine) monitor is exactly what this app was made for.

Secondly, this is not achieved by using hdmi-cec but this lib : [@kfix/ddcctl](https://github.com/kfix/ddcctl). It uses a feature/standard called display data channel. But, sadly, this standard is poorly supported/implemented and not by every monitor/tv manufacturer. So what's happening there may only be that your tv simply doesn't support it. 

In this case there's isn't really anything I can do, sorry 😞
