### ISSUE TITLE
Identical monitors cannot be distinguished

### ISSUE THREAD

**Issue by marknotton** [the0neyouseek/MonitorControl#6]
I was surprised to find that my VP2770-LED monitors supported DDC/CI; allowing your app to partially work. 

However, where I have two identical monitors, it seems the app can't tell them apart. In the menu bar, it lists both the monitors. They have the same name. It doesn't matter what monitor I adjust the brightness on, it only adjusts one monitor (my primary display). 

_Also, the "Default" button wasn't working for me._ 

Let me know if there is any more information you'd like to know. Or any other tests I can do to help. Thanks for all your time and efforts on this.

**Comment by the0neyouseek** [comment]
Hi @marknotton ,

Thanks for the detailed issuer, I'll look into it and get back to you soon.

**Comment by the0neyouseek** [comment]
Hi again @marknotton ,

I've just pushed a commit that will hopefully fix your issue, could you test if it works now? If you don't have XCode, please tell me and I'll send you a `dmg` of the build.

Have a nice day.

**Comment by marknotton** [comment]
Hi @the0neyouseek, you work fast!

I don't have any experience with XCode unfortunately. I have it installed, and I've assigned my dev certificate to the project. But I'm unable to run anything. I'm getting this: 

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Is there an easy fix for this? Do I need to install/download any dependancies?

Alternatively, you might have to send that dmg of the build. 

Thanks :)

**Comment by the0neyouseek** [comment]
Hi,

Yes you need to have [Cocoapods](https://cocoapods.org/) installed and then launch the command 
```sh
$ pod install
```
from your terminal at the root of the projet.
I'll send you a dmg tonight ([~7pm GMT+1](https://www.timeanddate.com/worldclock/france/paris)) if you still need it.

**Comment by the0neyouseek** [comment]
So, after looking a bit more on how to fix this I found this [issue](https://github.com/kfix/ddcctl/issues/17) on the DDCCTL repo. 
As it seems to be an upstream issue, there's nothing much I can do, so I'm closing this for now and will update if there's any change from DDCCTL.
