### ISSUE TITLE
Fn key is not working even on ver 1.3.0

### ISSUE THREAD

**Issue by meow2** [the0neyouseek/MonitorControl#60]
Hi, @the0neyouseek , thank you very much for developing this app! I'm a big fun of it.

Currently, I can't use (fn + F1) or (fn + F2) to adjust brightness (also to adjust sound with F10-12). As other users have reported, F1, F2, F10, F11, and F12 are overwritten as though I checked "Use F1, F2, etc. keys as standard function keys" in Keyboad, System Preferences. 

I'm using MacBook Pro Mid 2014 with LG 24UD58, and also "⌘英かな.app", which is a key changer app enabling left and right command keys to work as Japanese substitution keys. But this seems to have nothing to do with MonitorControl, because the problems still remains after I quit ⌘英かな.app.

Would be very appreciated if you fixed this bug.

Thank you in advance.

**Comment by mlauria93** [comment]
Same bug here Function keys aren’t working at all nor the volume neither the brightness: I am using an LG 32UD99-W connected via Type-C to a MBP(2017)

**Comment by kostya-666** [comment]
https://github.com/JoniVR/MonitorControl/releases/tag/1.3.1 fork build includes fix and works for me

**Comment by reitermarkus** [comment]
This should be fixed now.
