### ISSUE TITLE
v1.5.0 can't detect LG 34UM95-P Ultrawide monitor

### ISSUE THREAD

**Issue by gxfxyz** [the0neyouseek/MonitorControl#71]
Hello,

Firstly thank you for your good work. I've been waiting for a new release for a while.

I just upgraded MonitorControl to the latest v1.5.0 version. But I found it can't detect my LG [34UM95-P](https://www.lg.com/global/business/monitor/monitor-products/lg-34UM95-P) Ultrawide monitor in this version.

![Screen Shot 2019-05-07 at 14 58 10](https://user-images.githubusercontent.com/43481676/57336307-4c7db900-70da-11e9-93e5-4a244939c643.png)
![Screen Shot 2019-05-07 at 14 58 25](https://user-images.githubusercontent.com/43481676/57336318-556e8a80-70da-11e9-83a5-2073222a40f1.png)

After I downgraded it to v1.4.0, it's working again.

![Screen Shot 2019-05-07 at 14 59 43](https://user-images.githubusercontent.com/43481676/57336524-10972380-70db-11e9-94e4-0615c1ac25d2.png)
![Screen Shot 2019-05-07 at 15 00 01](https://user-images.githubusercontent.com/43481676/57336525-1260e700-70db-11e9-8936-276d5f0b0623.png)

So I guess this issue is related to the recent changes of LG Ultrawide monitors support in v1.5.0.

Let me know if you need more information. Thank you!

@reitermarkus

**Comment by reitermarkus** [comment]
This is hopefully fixed with the latest commit in `DDC.swift`.

**Comment by gxfxyz** [comment]
Can confirm this has been fixed in v1.5.2. Thank you guys for this great app! 👍
