### ISSUE TITLE
agvtool in "Sync Version Numbers" Run Script is making it impossible to build

### ISSUE THREAD

**Issue by JoniVR** [the0neyouseek/MonitorControl#76]
I'm not sure if I'm the only one or not, but I'm unable to build. 
Xcode will not throw an error or anything, the build will simply be "cancelled"

![image](https://user-images.githubusercontent.com/7591717/57369780-c4a5b680-718e-11e9-877e-2d24df786ec1.png)

I found this [stackoverflow question](https://stackoverflow.com/questions/16869159/archive-in-xcode-4-5-no-errors-but-build-cancelled) related to the issue, which says it's a problem with agvtool in run scripts, I tested this by removing the "sync version numbers" script and that seems to have fixed it.

**Comment by the0neyouseek** [comment]
Had to do the same thing to build

**Comment by reitermarkus** [comment]
Yes, I think it's because Xcode will reload the project when it is changed by `avgtool`.

Are you sure it is the Sync Version Numbers script and not the Increase Build Number script?

**Comment by JoniVR** [comment]
After some more testing, seems like it's either one of the scripts. 
If I remove either "Increase Build Number" or "Sync Version Numbers", clean and then build it will fail at first attempt, but if I build a second time after that it will succeed.
