### ISSUE TITLE
Native Volume Control on Keyboard stops working with program open

### ISSUE THREAD

**Issue by Amir-Hass** [the0neyouseek/MonitorControl#8]
On version 1.1, the volume wheel on my keyboard stops working, the HUD still shows up but it doesn't change volume. Selecting the volume in my menu bar still works, but I must quit the program to use my volume wheel.
F1/F2 also doesn't change my brightness, unless I'm missing something.

**Comment by the0neyouseek** [comment]
Hi Amir,

In this version I changed the way I handle the keyboard shortcuts to use the native mac keys. It should work if you have an apple keyboard, but if you have a third party keyboard you should use an utility like [Karabiner Elements](https://github.com/tekezo/Karabiner-Elements) to map your function keys to the correct mac equivalent (brightness up/down for <kbd>F1</kbd> & <kbd>F2</kbd>, mute, volume up/down for <kbd>F10</kbd>, <kbd>F11</kbd> and <kbd>F12</kbd>).

Tell me if it works for you

**Comment by Amir-Hass** [comment]
Installed Karabiner Elements, using their shortcut for volume and the volume wheel on my Corsair K70 (third party keyboard), doesn't change volume. Must go through Apple menu when MonitorControl is running.

**Comment by the0neyouseek** [comment]
Hi @Amir-Hass,

I'm currently working on a fix. It should be out this weekend.

Have a nice day. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Amir-Hass** [comment]
Hey man, just wondering if you've got an update on this? I'm very fond of your program!

**Comment by the0neyouseek** [comment]
Hi Amir,

I wasn't home for a bit so I didn't have time to look at this but will be sure to do that next weekend

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by the0neyouseek** [comment]
Hi @Amir-Hass ,

I've just pushed an update which hopefully fixes your issue. You should now be able to use your default function keys with the app.

Tell me if works for you, If not I'll re-open the issue,  
Have a nice day.
