### ISSUE TITLE
[Feature Request] Sound effect when changing volume level

### ISSUE THREAD

**Issue by ammmze** [the0neyouseek/MonitorControl#84]
First and foremost ... Thanks for this awesome app!

This is totally a nice to have feature, but any chance we'll see the ability to get the sound effect when changing volume levels like you get when changing volume levels natively? It's just nice because it gives you a quick indication of how loud the volume actually is via your ear sensors instead of eye sensors :)

**Comment by the0neyouseek** [comment]
Hi @ammmze,
That's an excellent idea !

**Comment by ammmze** [comment]
Wow...that was pretty quick 🙂 can't wait to try it next time I'm at my computer! Thank you
