### ISSUE TITLE
Keyboard not working & no contrast control

### ISSUE THREAD

**Issue by dzg** [the0neyouseek/MonitorControl#9]
On my machine, there are no keyboard shortcuts shown in the popup, and no contrast control.

Also, keyboard shortcuts do not work. (Using FunctionFlip.)

Thanks

![image](https://user-images.githubusercontent.com/466557/34718797-69eda1ea-f538-11e7-9879-668ab2740514.png)

**Comment by the0neyouseek** [comment]
Hi @dzg,

The screenshot on the Readme isn't up to date. Int he current version I've removed the contrast slider as I plan to have it only if you choose to in a preference window.

For the keyboard shortcut I currently use an Apple Keyboard so I didn't test with a third party keyboard nor FunctionFlip but as for the contrast, I plan to have a preference to choose if you want the app to listen for function keys or native Mac keys in v`1.2`. 

Hang tight, I'm hoping to push the update by the end of the week.

Have a nice day

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nekrasovdmitriy** [comment]
I can confirm that there is no F1/F2 hotkeys support even on wired Mac keyboard (with numeric keypad), app is added in security preferences. Also, contrast adjust is absolutely necessary, for example I have ViewSonic with ambient light sensor — when it is on, it locks brightness slider and you can additionally adjust brightness only by contrast control. So please, bring it back.

**Comment by the0neyouseek** [comment]
Hello @dzg & @nekrasovdmitriy ,

I've pushed an updated version of the app (`1.2`) which should fix this issue. Tell me if it works for you or not (if so I'll re-open this issue).

Thanks, have a nice day.
