### ISSUE TITLE
UHD Graphics 620 not detected

### ISSUE THREAD

**Issue by htpcrig** [the0neyouseek/MonitorControl#92]
Hi
I have Acer Swift 3. the UHD Graphics 620 is not being detected.

**Comment by JoniVR** [comment]
Hi @htpcrig 

So I'm assuming it's a Hackintosh? What display are you using? 

Do you know if it supports [DDC](https://en.wikipedia.org/wiki/Display_Data_Channel)?

If DDC is not supported then there is nothing we can do.

**Comment by the0neyouseek** [comment]
Closed, see #61
