### ISSUE TITLE
After updating to v1.5.0, MonitorControl no longer detects my screen (LG 25UM65, DisplayPort)

### ISSUE THREAD

**Issue by carlosfilhoadm** [the0neyouseek/MonitorControl#93]
Thank you for continuing to work on the app and releasing an update.

Unfortunately for me, however, after installing v1.5.0 my DisplayPort-connected screen is no longer detected by the app.

It's the same as #71 except my device is a different model (LG 25UM65).

I'll just have to downgrade for now, and wait for v.1.6.0.

**Comment by the0neyouseek** [comment]
Hi, Is this fixed for you in v1.5.2 ?

**Comment by carlosfilhoadm** [comment]
Thank you for releasing another update so quickly.

The new version detects both my screens again and the sliders work, although only for the primary screen -- same as #95 (both my screens are the same model, and all the sliders for both devices affect only the primary one).

Also, the keyboard keys for setting brightness and volume (along with the on-screen notification) stopped working. The app is on the list of Accessibility Features (System Settings > Security & Privacy > Privacy > Accessibility). I use a common PC wireless keyboard (with a USB dongle) and the keys worked in v1.3.0.

**Comment by JoniVR** [comment]
> Also, the keyboard keys for setting brightness and volume (along with the on-screen notification) stopped working. The app is on the list of Accessibility Features (System Settings > Security & Privacy > Privacy > Accessibility). I use a common PC wireless keyboard (with a USB dongle) and the keys worked in v1.3.0.

Have you tried removing MonitorControl from Accessibility settings and then relaunching the app and adding it again? 

Try the following:
1. Close MonitorControl if it's running
2. Remove MonitorControl from Accessibility settings
3. Launch MonitorControl (it will prompt for Accessibility settings)
4. Grant Accessibility Permissions
5. Restart the app

This sometimes happens. Removing and readding it seems to fix it usually. You also need to manually restart the app after granting permissions, this is something that we're working on making more user friendly in future versions.

**Comment by the0neyouseek** [comment]
Closed, please fill free to comment is this is still a problem for you.
