### ISSUE TITLE
No mute when turning volume all the way down on Samsung C34J79

### ISSUE THREAD

**Issue by larskochhansen** [the0neyouseek/MonitorControl#94]
I just bought a new Samsung Curved monitor for my MBP2018. The MonitorControl works very nicely but I cannot mute the sound. When I use the hotkeys to turn the volume all the way down it's still play at a low volume. The same when I press the mute button on my keyboard (the icon shows mute).

I'm not sure why this is happening.

**Comment by the0neyouseek** [comment]
Hi !
What I'm guessing is going on here is that the min value is below the standard "0". Do you have the same problem using the display native OSD ?

**Comment by larskochhansen** [comment]
No. Only when controlling the volume using the Monitor Control. It mutes fine using the built in monitor control. 

Is it possible to change the range of max/min in order the fix this? 

Best wishes 
Lars
Sendt fra iPhone X

**Comment by the0neyouseek** [comment]
cc #96

**Comment by larskochhansen** [comment]
Thanks for the prompt replies. Looking forward to a solution. I'll close this topic. Thanks again.
