### ISSUE TITLE
When using monitors of the same model, only the first is controlled

### ISSUE THREAD

**Issue by usr-sse2** [the0neyouseek/MonitorControl#95]
I have two Lenovo monitors, one is connected through HDMI and the second through DisplayPort. Both are shown in MonitorControl, and brightness sliders of both displays change the brightness of HDMI one.

**Comment by usr-sse2** [comment]
Model: LEN T2454pA

**Comment by carlosfilhoadm** [comment]
I confirm this happens on my setup (two LG 25UM65, both connected through DisplayPort to a Mac Mini running Mojave).

All the sliders for both devices affect only the primary one.

**Comment by the0neyouseek** [comment]
Closed, see #49 for further discussions
