### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by MarcoCarnevali** [the0neyouseek/MonitorControl#98]
Hello! I can translate it to Italian if you need it :)

**Comment by the0neyouseek** [comment]
Hi @MarcoCarnevali 😄 

Please feel free to do that and open a pull request I you're familiar with XCode.
You can use [Bartycrouch](https://github.com/Flinesoft/BartyCrouch) to generate translation files and keep them organized.

There are 3 translations files for each language :

- `MonitorControl/Support/<your-language>.lproj/Localizable.strings`
- `MonitorControl/UI/<your-language>.lproj/Main.strings`
- `MonitorControl/UI/<your-language>.lproj/MainMenu.strings`

If you're not familiar at all with XCode just wait a little bit, I'm gonna publish them on an open source tools to ease future translations.

**Comment by MarcoCarnevali** [comment]
#1

**Comment by MarcoCarnevali** [comment]
#italiantranslation

**Comment by MarcoCarnevali** [comment]
> Hi @MarcoCarnevali 😄
> 
> Please feel free to do that and open a pull request I you're familiar with XCode.
> You can use [Bartycrouch](https://github.com/Flinesoft/BartyCrouch) to generate translation files and keep them organized.
> 
> There are 3 translations files for each language :
> 
> * `MonitorControl/Support/<your-language>.lproj/Localizable.strings`
> * `MonitorControl/UI/<your-language>.lproj/Main.strings`
> * `MonitorControl/UI/<your-language>.lproj/MainMenu.strings`
> 
> If you're not familiar at all with XCode just wait a little bit, I'm gonna publish them on an open source tools to ease future translations.

just created the pull request ;)

**Comment by JoniVR** [comment]
Added in v1.7.0
